# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VenturaHRMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VenturaHRMobile
  pod "Firebase/Auth"
  pod "Firebase/Firestore"
  pod 'Firebase/Core'
  pod 'FirebaseFirestoreSwift'
  pod "DropDown"
  pod "JMMaskTextField-Swift"


  target 'VenturaHRMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
